# Generated by Django 5.1.5 on 2025-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
