# Generated by Django 5.1.6 on 2025-02-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='cv_personne',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
