# Generated by Django 5.1.5 on 2025-01-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0002_cv_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='prenom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
