# Generated by Django 5.1.5 on 2025-01-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0003_cv_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='prenom',
        ),
    ]
