# Generated by Django 5.1.5 on 2025-01-30 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0004_remove_cv_nom_remove_cv_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
    ]
