# Generated by Django 5.1.5 on 2025-01-30 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0005_remove_cv_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='telephone',
        ),
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcv.contact'),
            preserve_default=False,
        ),
    ]
